name: Update Dependencies

on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Update dependencies
        run: |
          poetry update
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: "Update dependencies to their latest versions"
          branch: "chore/update-dependencies"
          base: "main" 